// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Accounts.proto

#include "Accounts.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_Accounts_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Accounts_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PBAccount;
}  // namespace protobuf_Accounts_2eproto
class PBAccountDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBAccount>
      _instance;
} _PBAccount_default_instance_;
class PBAccountsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBAccounts>
      _instance;
} _PBAccounts_default_instance_;
namespace protobuf_Accounts_2eproto {
static void InitDefaultsPBAccount() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PBAccount_default_instance_;
    new (ptr) ::PBAccount();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PBAccount::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PBAccount =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPBAccount}, {}};

static void InitDefaultsPBAccounts() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_PBAccounts_default_instance_;
    new (ptr) ::PBAccounts();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PBAccounts::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PBAccounts =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPBAccounts}, {
      &protobuf_Accounts_2eproto::scc_info_PBAccount.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PBAccount.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PBAccounts.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, balance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, accountnum_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, dateopened_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccount, ssn_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccounts, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PBAccounts, accounts_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::PBAccount)},
  { 10, -1, sizeof(::PBAccounts)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PBAccount_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PBAccounts_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Accounts.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016Accounts.proto\"_\n\tPBAccount\022\017\n\007balance"
      "\030\001 \001(\002\022\014\n\004name\030\002 \001(\t\022\022\n\naccountNum\030\003 \001(\005"
      "\022\022\n\ndateOpened\030\004 \001(\t\022\013\n\003SSN\030\005 \001(\t\"*\n\nPBA"
      "ccounts\022\034\n\010accounts\030\001 \003(\0132\n.PBAccountb\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 165);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Accounts.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Accounts_2eproto

// ===================================================================

void PBAccount::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBAccount::kBalanceFieldNumber;
const int PBAccount::kNameFieldNumber;
const int PBAccount::kAccountNumFieldNumber;
const int PBAccount::kDateOpenedFieldNumber;
const int PBAccount::kSSNFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBAccount::PBAccount()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Accounts_2eproto::scc_info_PBAccount.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PBAccount)
}
PBAccount::PBAccount(const PBAccount& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  dateopened_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.dateopened().size() > 0) {
    dateopened_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dateopened_);
  }
  ssn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ssn().size() > 0) {
    ssn_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ssn_);
  }
  ::memcpy(&balance_, &from.balance_,
    static_cast<size_t>(reinterpret_cast<char*>(&accountnum_) -
    reinterpret_cast<char*>(&balance_)) + sizeof(accountnum_));
  // @@protoc_insertion_point(copy_constructor:PBAccount)
}

void PBAccount::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dateopened_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ssn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&balance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&accountnum_) -
      reinterpret_cast<char*>(&balance_)) + sizeof(accountnum_));
}

PBAccount::~PBAccount() {
  // @@protoc_insertion_point(destructor:PBAccount)
  SharedDtor();
}

void PBAccount::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dateopened_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ssn_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PBAccount::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBAccount::descriptor() {
  ::protobuf_Accounts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Accounts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBAccount& PBAccount::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Accounts_2eproto::scc_info_PBAccount.base);
  return *internal_default_instance();
}


void PBAccount::Clear() {
// @@protoc_insertion_point(message_clear_start:PBAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dateopened_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ssn_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&balance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&accountnum_) -
      reinterpret_cast<char*>(&balance_)) + sizeof(accountnum_));
  _internal_metadata_.Clear();
}

bool PBAccount::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PBAccount)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float balance = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &balance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PBAccount.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 accountNum = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &accountnum_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string dateOpened = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dateopened()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dateopened().data(), static_cast<int>(this->dateopened().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PBAccount.dateOpened"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string SSN = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ssn()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ssn().data(), static_cast<int>(this->ssn().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PBAccount.SSN"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PBAccount)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PBAccount)
  return false;
#undef DO_
}

void PBAccount::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PBAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float balance = 1;
  if (this->balance() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->balance(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  // int32 accountNum = 3;
  if (this->accountnum() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->accountnum(), output);
  }

  // string dateOpened = 4;
  if (this->dateopened().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dateopened().data(), static_cast<int>(this->dateopened().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.dateOpened");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->dateopened(), output);
  }

  // string SSN = 5;
  if (this->ssn().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ssn().data(), static_cast<int>(this->ssn().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.SSN");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->ssn(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PBAccount)
}

::google::protobuf::uint8* PBAccount::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PBAccount)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float balance = 1;
  if (this->balance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->balance(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  // int32 accountNum = 3;
  if (this->accountnum() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->accountnum(), target);
  }

  // string dateOpened = 4;
  if (this->dateopened().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dateopened().data(), static_cast<int>(this->dateopened().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.dateOpened");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->dateopened(), target);
  }

  // string SSN = 5;
  if (this->ssn().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ssn().data(), static_cast<int>(this->ssn().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PBAccount.SSN");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->ssn(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBAccount)
  return target;
}

size_t PBAccount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBAccount)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string dateOpened = 4;
  if (this->dateopened().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dateopened());
  }

  // string SSN = 5;
  if (this->ssn().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ssn());
  }

  // float balance = 1;
  if (this->balance() != 0) {
    total_size += 1 + 4;
  }

  // int32 accountNum = 3;
  if (this->accountnum() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->accountnum());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBAccount::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PBAccount)
  GOOGLE_DCHECK_NE(&from, this);
  const PBAccount* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBAccount>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PBAccount)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PBAccount)
    MergeFrom(*source);
  }
}

void PBAccount::MergeFrom(const PBAccount& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBAccount)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.dateopened().size() > 0) {

    dateopened_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dateopened_);
  }
  if (from.ssn().size() > 0) {

    ssn_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ssn_);
  }
  if (from.balance() != 0) {
    set_balance(from.balance());
  }
  if (from.accountnum() != 0) {
    set_accountnum(from.accountnum());
  }
}

void PBAccount::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PBAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBAccount::CopyFrom(const PBAccount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBAccount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBAccount::IsInitialized() const {
  return true;
}

void PBAccount::Swap(PBAccount* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBAccount::InternalSwap(PBAccount* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  dateopened_.Swap(&other->dateopened_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  ssn_.Swap(&other->ssn_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(balance_, other->balance_);
  swap(accountnum_, other->accountnum_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBAccount::GetMetadata() const {
  protobuf_Accounts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Accounts_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PBAccounts::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBAccounts::kAccountsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBAccounts::PBAccounts()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Accounts_2eproto::scc_info_PBAccounts.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:PBAccounts)
}
PBAccounts::PBAccounts(const PBAccounts& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      accounts_(from.accounts_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PBAccounts)
}

void PBAccounts::SharedCtor() {
}

PBAccounts::~PBAccounts() {
  // @@protoc_insertion_point(destructor:PBAccounts)
  SharedDtor();
}

void PBAccounts::SharedDtor() {
}

void PBAccounts::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBAccounts::descriptor() {
  ::protobuf_Accounts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Accounts_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBAccounts& PBAccounts::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Accounts_2eproto::scc_info_PBAccounts.base);
  return *internal_default_instance();
}


void PBAccounts::Clear() {
// @@protoc_insertion_point(message_clear_start:PBAccounts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  accounts_.Clear();
  _internal_metadata_.Clear();
}

bool PBAccounts::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PBAccounts)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PBAccount accounts = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_accounts()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PBAccounts)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PBAccounts)
  return false;
#undef DO_
}

void PBAccounts::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PBAccounts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PBAccount accounts = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->accounts_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->accounts(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PBAccounts)
}

::google::protobuf::uint8* PBAccounts::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PBAccounts)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .PBAccount accounts = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->accounts_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->accounts(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PBAccounts)
  return target;
}

size_t PBAccounts::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PBAccounts)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .PBAccount accounts = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->accounts_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->accounts(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBAccounts::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PBAccounts)
  GOOGLE_DCHECK_NE(&from, this);
  const PBAccounts* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBAccounts>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PBAccounts)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PBAccounts)
    MergeFrom(*source);
  }
}

void PBAccounts::MergeFrom(const PBAccounts& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PBAccounts)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  accounts_.MergeFrom(from.accounts_);
}

void PBAccounts::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PBAccounts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBAccounts::CopyFrom(const PBAccounts& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PBAccounts)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBAccounts::IsInitialized() const {
  return true;
}

void PBAccounts::Swap(PBAccounts* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBAccounts::InternalSwap(PBAccounts* other) {
  using std::swap;
  CastToBase(&accounts_)->InternalSwap(CastToBase(&other->accounts_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBAccounts::GetMetadata() const {
  protobuf_Accounts_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Accounts_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PBAccount* Arena::CreateMaybeMessage< ::PBAccount >(Arena* arena) {
  return Arena::CreateInternal< ::PBAccount >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::PBAccounts* Arena::CreateMaybeMessage< ::PBAccounts >(Arena* arena) {
  return Arena::CreateInternal< ::PBAccounts >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
