FROM ubuntu

RUN sudo apt-get update
RUN sudo apt-get install emacs
RUN sudo apt-get install build-essential
RUN sudo apt-get install libc6-dbg gdb valgrind
RUN sudo apt-get install git-all
RUN sudo apt-get install zip
RUN sudo apt-get install zip
RUN sudo apt-get install curl
RUN sudo apt-get install htop
RUN sudo apt-get install iftop
RUN sudo apt-get install iotop
RUN sudo apt-get install cscope
RUN sudo apt-get install tree

#Install "Development Tools", gdb, zip, curl, htop, iftop, iotop, cscope, tree.

#Set up a standard ".profile" or ".bashrc" that is included with your Dockerfile, so you have a standardized environment. Upon starting the docker container, your profile should be automatically sourced.

#Set HomeDir